---
spec/spec_helper.rb:
  coverage_report: true
  mock_with: ':rspec'

.github/workflows/ci.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
